name: OriFramework
main: xyz.oribuin.gui.plugin.OriFramework
version: '1.0.3'
authors: [ Oribuin ]
api-version: '1.15'
description: Example plugin to showcase ori's gui framework
commands:
  guiframework:
    description: Main plugin command.
    usage: /guiframework